package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class PropertiesIcons {
  private static Image load(String path) {
    return IconLoader.getIcon(path, PropertiesIcons.class);
  }

  public static final Image XmlProperties = load("/icons/xmlProperties.png"); // 16x16
}
